bbs/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog import views
from django.views.static import serve
from django.conf import settings
from blog import urls as blog_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', views.login),
    url(r'^logout/', views.logout),
    url(r'^register/', views.register),

    # 将所有以blog开头的URL交给blog_urls处理
    url(r'^blog/', include(blog_urls)),

    # 主页
    url(r'^index/', views.index),

    # 极验滑动验证码 获取验证码的url
    url(r'^pc-geetest/register', views.get_geetest),

    # 专门用来校验用户名是否已被注册的接口
    url(r'^check_username_exist/$', views.check_username_exist),

    # 上传url
    url(r'^upload/', views.upload),


    url(r'^media/(?P<path>.*)$',serve,{"document_root":settings.MEDIA_ROOT}),
    url(r"backend/add_article/", views.add_article),
    url(r'^backend/$', views.cn_backend),
    # 删除
    url(r'^delete/$', views.delete),
    # 编辑
    url(r'^backend/edit_article/(?P<article_id>\w+)$', views.edit_article),

]

blog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class UserInfo(AbstractUser):
    """
    用户信息表
    """
    nid = models.AutoField(primary_key=True)
    phone = models.CharField(max_length=11, null=True, unique=True)
    avatar = models.FileField(upload_to="avatars/", default="avatars/default.png", verbose_name="头像")
    create_time = models.DateTimeField(auto_now_add=True)
    blog = models.OneToOneField(to="Blog", to_field="nid", null=True,on_delete=models.CASCADE)

    def __str__(self):
        return self.username
    class Meta:
        verbose_name = "用户"
        verbose_name_plural = verbose_name


class Blog(models.Model):
    """
    博客信息
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=64)              # 个人博客标题
    site = models.CharField(max_length=32, unique=True)  # 个人博客后缀
    theme = models.CharField(max_length=32)              # 博客主题

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "blog站点"
        verbose_name_plural = verbose_name


class Category(models.Model):
    """
    个人博客文章分类
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=32)  # 分类标题
    blog = models.ForeignKey(to="Blog", to_field="nid",on_delete=models.CASCADE)  # 外键关联博客，一个博客站点可以有多个分类

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "文章分类"
        verbose_name_plural = verbose_name


class Tag(models.Model):
    """
    标签
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=32)  # 标签名
    blog = models.ForeignKey(to="Blog", to_field="nid",on_delete=models.CASCADE)  # 所属博客

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "标签"
        verbose_name_plural = verbose_name


class Article(models.Model):
    """
    文章
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50, verbose_name="文章标题")  # 文章标题
    desc = models.CharField(max_length=255)                          # 文章描述
    create_time = models.DateTimeField(auto_now_add=True)            # 创建时间

    # 评论数
    comment_count = models.IntegerField(verbose_name="评论数", default=0)
    # 点赞数
    up_count = models.IntegerField(verbose_name="点赞数", default=0)
    # 踩
    down_count = models.IntegerField(verbose_name="踩数", default=0)

    category = models.ForeignKey(to="Category", to_field="nid", null=True,on_delete=models.CASCADE)
    user = models.ForeignKey(to="UserInfo", to_field="nid",on_delete=models.CASCADE)
    tags = models.ManyToManyField(  # 中介模型
        to="Tag",
        through="Article2Tag",
        through_fields=("article", "tag"),  # 注意顺序！！！
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = verbose_name


class ArticleDetail(models.Model):
    """
    文章详情表
    """
    nid = models.AutoField(primary_key=True)
    content = models.TextField()
    article = models.OneToOneField(to="Article", to_field="nid",on_delete=models.CASCADE)

    class Meta:
        verbose_name = "文章详情"
        verbose_name_plural = verbose_name
    def __str__(self):
        return self.article.title


class Article2Tag(models.Model):
    """
    文章和标签的多对多关系表
    """
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(to="Article", to_field="nid",on_delete=models.CASCADE)
    tag = models.ForeignKey(to="Tag", to_field="nid",on_delete=models.CASCADE)

    class Meta:
        unique_together = (("article", "tag"),)
        verbose_name = "文章-标签"
        verbose_name_plural = verbose_name
    def __str__(self):
        return "{}-{}".format(self.article.title,self.tag.title)


class ArticleUpDown(models.Model):
    """
    点赞表
    """
    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey(to="UserInfo", null=True,on_delete=models.CASCADE)
    article = models.ForeignKey(to="Article", null=True,on_delete=models.CASCADE)
    is_up = models.BooleanField(default=True)

    class Meta:
        unique_together = (("article", "user"),)  #联合唯一 一个用户只能对一篇文章进行某个赞操作
                                                  #不能出现 一个用户对一篇文章既点赞又点踩
        verbose_name = "文章点赞"
        verbose_name_plural = verbose_name


class Comment(models.Model):
    """
    评论表
    """
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(to="Article", to_field="nid",on_delete=models.CASCADE)
    user = models.ForeignKey(to="UserInfo", to_field="nid",on_delete=models.CASCADE)
    content = models.CharField(max_length=255)  # 评论内容
    create_time = models.DateTimeField(auto_now_add=True)
    parent_comment = models.ForeignKey("self", null=True, blank=True,on_delete=models.CASCADE)  # blank=True 在django admin里面可以不填

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = "评论"
        verbose_name_plural = verbose_name

blog/forms.py
"""
bbs用到的form类
"""
from django import forms
from django.core.exceptions import ValidationError
from blog import models

# 定义一个注册的form类
class RegForm(forms.Form):
    username = forms.CharField(
        max_length=16,
        label="用户名",
        error_messages={
            "max_length": "用户名最长16位",
            "required": "用户名不能为空",
        },

        widget=forms.widgets.TextInput(
            attrs={"class": "form-control"},
        )
    )

    password = forms.CharField(
        min_length=6,
        label="密码",
        widget=forms.widgets.PasswordInput(
            attrs={"class": "form-control"},
            render_value=True,
        ),
        error_messages={
            "min_length": "密码至少要6位！",
            "required": "密码不能为空",
        }
    )

    re_password = forms.CharField(
        min_length=6,
        label="确认密码",
        widget=forms.widgets.PasswordInput(
            attrs={"class": "form-control"},
            render_value=True,
        ),
        error_messages={
            "min_length": "确认密码至少要6位！",
            "required": "确认密码不能为空",
        }
    )

    email = forms.EmailField(
        label="邮箱",
        widget=forms.widgets.EmailInput(
            attrs={"class": "form-control"},

        ),
        error_messages={
            "invalid": "邮箱格式不正确！",
            "required": "邮箱不能为空",
        }
    )

    # 重写username字段的局部钩子
    def clean_username(self):
        username = self.cleaned_data.get("username")
        is_exist = models.UserInfo.objects.filter(username=username)
        if is_exist:
            # 表示用户名已注册
            self.add_error("username", ValidationError("用户名已存在"))
        else:
            return username


    # 重写email字段的局部钩子
    def clean_email(self):
        email = self.cleaned_data.get("email")
        is_exist = models.UserInfo.objects.filter(email=email)
        if is_exist:
            # 表示邮箱已注册
            self.add_error("email", ValidationError("邮箱已被注册"))
        else:
            return email

    # 重写全局的钩子函数，对确认密码做校验
    def clean(self):
        password = self.cleaned_data.get("password")
        re_password = self.cleaned_data.get("re_password")

        if re_password and re_password != password:
            self.add_error("re_password", ValidationError("两次密码不一致"))
        else:
            return self.cleaned_data

templates/add_article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加文章</title>
    <style>
        * {
            margin: 0;
        }

        .content {
            width: 80%;
            margin: 20px auto;
        }
    </style>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <script src="/static/js/jquery-3.3.1.js"></script>
</head>
<body>

<div class="header">
    <div class="site-header">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                </div>
                <a class="navbar-brand" href="/index/">博客小屋</a>
            </div>
        </nav>
    </div>
</div>
<div class="content">
    <h3>添加文章</h3>
    <form action="" method="post">
        {% csrf_token %}
        <div>
            <label for="">文章标题</label>
            <input type="text" name="title" class="form-control" style="width: 800px">
        </div>

        <div>
            <p>内容(TinyMCE编辑器，支持拖放/粘贴上传图片) </p>
            <textarea name="article_content" id="article_content" cols="60" rows="20"></textarea>
        </div>
        <input type="submit" class="btn btn-info">
    </form>
</div>

<script charset="utf-8" src="/static/kindeditor/kindeditor-all.js"></script>
<script>
    KindEditor.ready(function (K) {
        window.editor = K.create('#article_content', {
            width: "800",
            height: "500px",
            resizeType: 0,
            uploadJson: "/upload/",
            extraFileUploadParams: {
                csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val()
            },
            filePostName: "upload_img"

        });
    });
</script>
</body>
</html>

templates/article_detail.html
{% extends 'base.html' %}
{% block page-main %}
    <div class="article-detail">
        <h1 style="text-align: center;font-weight: bold">{{ article.title }}</h1>
        <p>{{ article.articledetail.content|safe }}</p>
    </div>

    <!--点赞开始-->

    <div class="poll clearfix">
        <div id="div_digg">
            <div class="diggit action">
                <span class="diggnum" id="digg_count">{{ article.up_count }}</span>
            </div>
            <div class="buryit action">
                <span class="burynum" id="bury_count">{{ article.down_count }}</span>
            </div>
            <div class="clear"></div>
            <div class="diggword" id="digg_tips" style="color: red;"></div>
        </div>
        <div class="info" username="{{ request.user.username }}"></div>
    </div>
    <!--点赞结束-->


    <!--评论开始-->
    <p>评论树</p>

    <ul class="comment_tree list-group">

    </ul>

    <p>评论列表</p>
    <ul class="comment_list">
        {% for comment in comment_list %}
            <li class="list-group-item">
                <div>
                    <a href="">#{{ forloop.counter }}楼</a> &nbsp;&nbsp;
                    <span style="color: gray">{{ comment.create_time|date:"Y-m-d H:i" }}</span> &nbsp;&nbsp;
                    <a href=""><span>{{ comment.user.username }}</span></a>
                    <a class="pull-right reply_btn" username="{{ comment.user.username }}"
                       comment_pk="{{ comment.nid }}"><span>回复</span></a>
                </div>

                {% if comment.parent_comment_id %}
                    <div class="pid-info well">
                        <p>{{ comment.parent_comment.user.username }}:&nbsp;&nbsp;&nbsp;{{ comment.parent_comment.content }}</p>
                    </div>
                {% endif %}

                <div class="con">
                    <p>
                        {{ comment.content }}
                    </p>
                </div>
            </li>
        {% endfor %}
    </ul>

    {% if request.user.username %}
        <div class="div_comment">
            <p>
                昵称：<input type="text" id="tbCommentAuthor" class="author" disabled="disabled" size="50"
                          value="{{ request.user.username }}">
            </p>
            <p>评论内容</p>
            <textarea name="" id="comment_content" cols="60" rows="10">

        </textarea>
            <p>
                <button id="comment_btn">提交评论</button>
            </p>
        </div>
    {% else %}
        <a href="/login/">评论前需要登录</a>
    {% endif %}


    <!--评论结束-->

    {% csrf_token %}
    <script>
        $.ajax({
            url:"blog/comment_tree/{{ article.pk }}/",
            success:function (data) {
                console.log(data);
                $.each(data,function (index,comment_dict) {
                    if(comment_dict.parent_comment_id){
                        //子评论
                        var s = '<li class="list-group-item comment_item" comment_id=' + comment_dict.pk + '> <span class="content">' + comment_dict.content + '</span> </li>'
                        pid=comment_dict.parent_comment_id;

                        //利用属性选择器找到comment_id=父ID的DIV，然后添加进去
                        $("[comment_id="+pid+"]").append(s)
                    }else{
                        //根评论直接添加到评论树的div中
                        var s = '<li class="well list-group-item comment_item" comment_id=' + comment_dict.pk + '> <span class="content">' + comment_dict.content + '</span> </li>'
                        $(".comment_tree").append(s)
                    }
                })
            }
        })

        $("#div_digg .action").click(function () {
            //点赞或者踩灭
            if ($(".info").attr("username")) {
                var is_up = $(this).hasClass("diggit");
                var article_id = "{{ article.pk }}";
                $.ajax({
                    url: "/blog/up_down/",
                    type: "post",
                    data: {
                        is_up: is_up,
                        article_id: article_id,
                        csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val(),
                    },
                    success: function (data) {
                        if (data.status) {
                            //提交过去数据
                            if (is_up) {
                                var val = $("#digg_count").text();
                                val = parseInt(val) + 1;
                                $("#digg_count").text(val);
                            } else {
                                var val = $("#bury_count").text();
                                val = parseInt(val) + 1;
                                $("#bury_count").text(val);

                            }
                        } else {  //重复提交
                            if (data.first_action) {
                                $("#digg_tips").text("您已经推荐过了")
                            } else {
                                $("#digg_tips").text("您已经反对过了")
                            }
                            setTimeout(function () {
                                $("#digg_tips").html("")
                            }, 2000)

                        }
                    }
                })
            } else {
                location.href = "/login/"
            }

        })

        //提交评论
        var pid = "";
        $("#comment_btn").click(function () {
            var article_id = "{{ article.pk }}";
            var content = $("#comment_content").val();
            if (pid) {
                var index = content.indexOf("\n")
                content = content.slice(index + 1)
            }
            $.ajax({
                url: "/blog/comment/",
                type: "post",
                data: {
                    article_id: article_id,
                    pid: pid,
                    content: content,
                    csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val(),
                },
                success: function (data) {
                    var create_time = data.create_time;
                    var content_1 = data.content;
                    var username = data.username;
                    console.log(data.content)
                    //评论完清空评论框
                    var content = $("#comment_content").val("");

                    //发送完应该清空父ID，不然不刷新的话即使没回复也有pid
                    pid = "";

                    //取到这个LI标签，从数据库取到必要的内容拼接取来，然后生成一个新的DOM
                    var comment_li = '<li class="list-group-item"><div><span style="color: gray">' + create_time + '</span> &nbsp;&nbsp; <a href=""><span>' + username + '</span></a></div> <div class="con"> <p> ' + content_1 + ' </p> </div> </li>';

                    //添加一个dom操作。
                    $(".comment_list").append(comment_li);

                }
            })
        })

        //回复按钮事件
        $(".list-group-item .reply_btn").click(function () {
            $("#comment_content").focus();
            var v = "@" + $(this).attr("username") + "\n";
            $("#comment_content").val(v);
            //获取PID
            pid = $(this).attr("comment_pk")
        })

    </script>
{% endblock %}

templates/backend.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/js/mystyle.css">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/fontawesome/css/font-awesome.css">
    <link rel="stylesheet" href="/static/theme/{{ blog.theme }}">
    <link rel="stylesheet" href="/static/sweetalert/sweetalert.css">

    <title>后台管理</title>
</head>
<body>
<div class="header">
    <div class="site-header">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                </div>
                <a class="navbar-brand" href="/index/">博客小屋</a>
            </div>
        </nav>
    </div>
</div>

<div class="container">
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">操作</div>
            <div class="panel-body">
                <a href="/backend/add_article/">添加文章</a>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="tab-content">
            <div class="article_list small">
                <table class="table table-hover table-striped">
                    {% csrf_token %}
                    <thead>
                    <th>序号</th>
                    <th>标题</th>
                    <th>评论数</th>
                    <th>点赞数</th>
                    <th>操作</th>
                    <th>操作</th>
                    </thead>

                    <tbody>
                    {% for article in article_list %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td class="article_id" style="display: none">{{ article.nid }}</td>
                            <td>
                                <a href="/blog/{{ request.user.username }}/article/{{ article.nid }}">{{ article.title }}</a>
                            </td>
                            <td>{{ article.comment_count }}</td>
                            <td>{{ article.up_count }}</td>
                            <td><a href="/backend/edit_article/{{ article.pk }}">编辑</a></td>
                            <td><a class="delete" style="cursor: pointer;">删除</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script src="/static/js/jquery-3.3.1.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
<script src="/static/sweetalert/sweetalert.min.js"></script>
<script type="text/javascript">
    $(function () {
        $('tr').on('click', 'td a.delete', function (e) {
            var article_id = $(e.target).parent().siblings('.article_id').html();
            var $trEle = $(this).parent().parent();
            swal({
                    title: "你确定要删除吗？",
                    text: "文章删除后不可恢复",
                    type: "info",
                    showCancelButton: true,
                    confirmButtonClass: "btn-info",
                    confirmButtonText: "确认",
                    cancelButtonText: "取消",
                    closeOnConfirm: false,
                    showLoaderOnConfirm: true
                },
                function () {
                    // 向后端发送删除的请求
                    $.ajax({
                        url: '/delete/',
                        type: 'post',
                        data: {
                            "csrfmiddlewaretoken": $("[name='csrfmiddlewaretoken']").val(),
                            article_id: article_id
                        },
                        success: function (data) {
                            if (data.status) {
                                swal("删除成功", "文章已经删除!", "success");
                                $trEle.remove();
                            }
                            else {
                                swal("删除失败", "取消成功!", "success");
                            }
                        }
                    })
                })

        })

    })
</script>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/js/mystyle.css">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/fontawesome/css/font-awesome.css">
    <link rel="stylesheet" href="/static/theme/{{ blog.theme }}">
    <script src="/static/js/jquery-3.3.1.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    <title>{{ blog.title }}</title>
</head>
<body>
<div class="header">
    <p style="padding-left: 25px">{{ blog.title }}</p>
</div>

<div class="container">
    <div class="col-md-3">
        {% load my_tags %}
        {% get_left_menu username %}
    </div>
    <div class="col-md-8">
        {% block page-main %}
        {% endblock %}
        <!---个人博客开始-->
    </div>
</div>
</body>
</html>

templates/edit_article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑文章</title>
    <style>
        * {
            margin: 0;
        }
        .content {
            width: 80%;
            margin: 20px auto;
        }
    </style>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
     <script src="/static/js/jquery-3.3.1.js"></script>
</head>
<body>

<div class="header">
    <div class="site-header">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                </div>
                <a class="navbar-brand" href="/index/">博客小屋</a>
            </div>
        </nav>
    </div>
</div>
<div class="content">
    <h3>编辑文章</h3>
    <form action="" method="post">
        {% csrf_token %}
        <div>
            <label for="">文章标题</label>
            <input type="text" name="title" class="form-control" style="width: 800px" value="{{ article_obj.title }}">
        </div>

        <div>
            <p>内容(TinyMCE编辑器，支持拖放/粘贴上传图片) </p>
            <textarea name="article_content" id="article_content" cols="60" rows="20">{{ origin_content.content }}</textarea>
        </div>
        <input type="submit" class="btn btn-info">
    </form>
</div>

<script charset="utf-8" src="/static/kindeditor/kindeditor-all.js"></script>
<script>
        KindEditor.ready(function(K) {
                window.editor = K.create('#article_content',{
                    width:"800",
                    height:"500px",
                    resizeType:0,
                    uploadJson:"/upload/",
                    extraFileUploadParams:{
                            csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val()
                    },
                    filePostName:"upload_img"

                });
        });
</script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block page-main %}

    <div class="article-list">
            {% for article in article_list %}
                <div class="article">
                    <p class="article-title"><a href="/blog/{{ article.user.username }}/article/{{ article.pk }}">{{ article.title }}</a></p>
                    <div class="media">
                        <div class="media-left">
                            <a >
                                <img class="media-object author-img" src="/media/{{ article.user.avatar }}">
                            </a>
                        </div>
                        <div class="media-body">
                            <p>{{ article.desc }}</p>
                        </div>
                    </div>
                    <div class="article-footer">
                        <span><a href="/blog/{{ article.user.username }}">{{ article.user.username }}</a></span>
                        <span>发布于{{ article.create_time|date:'Y-m-d H:i:s' }}</span>
                        <span><i class="fa fa-commenting" aria-hidden="true"></i>评论({{ article.comment_count }})</span>
                        <span><i class="fa fa-thumbs-o-up" aria-hidden="true"></i>点赞({{ article.up_count }})</span>
                    </div>
                    <hr>
                </div>
            {% endfor %}
            <!---个人博客列表结束-->
        </div>
{% endblock %}

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>欢迎注册</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/js/mystyle.css">
    <style>
        body {
            background: url(https://www.cnblogs.com/skins/UnlimitedSunlight/images/banner.jpg) fixed;
            background-repeat: no-repeat;
            background-color: #e2ddc7;
        }
    </style>
</head>
<body>
<h1 style="text-align: center;font-size: 40px;padding: 2%">账号注册</h1>
<div class="container" style=" opacity:0.7;">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form novalidate action="/register/" method="post" class="form-horizontal reg-form" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form_obj.username.id_for_label }}" class="col-sm-3 control-label">{{ form_obj.username.label }}</label>
                    <div class="col-sm-8">{{ form_obj.username }}<span class="help-block">{{ form_obj.username.errors.0 }}</span></div>
                </div>

                <div class="form-group">
                    <label for="{{ form_obj.password.id_for_label }}" class="col-sm-3 control-label">{{ form_obj.password.label }}</label>
                    <div class="col-sm-8">{{ form_obj.password }}<span class="help-block">{{ form_obj.password.errors.0 }}</span></div>
                </div>

                <div class="form-group">
                    <label for="{{ form_obj.re_password.id_for_label }}" class="col-sm-3 control-label">{{ form_obj.re_password.label }}</label>
                    <div class="col-sm-8">{{ form_obj.re_password }}<span class="help-block">{{ form_obj.re_password.errors.0 }}</span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="{{ form_obj.email.id_for_label }}" class="col-sm-3 control-label">{{ form_obj.email.label }}</label>
                    <div class="col-sm-8">{{ form_obj.email }}<span class="help-block">{{ form_obj.email.errors.0 }}</span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-3 control-label">头像</label>
                    <div class="col-sm-8">
                        <label style="margin-left: 35%" for="id_avatar"><img id="avatar-img" src="/media/avatars/default.png" alt=""></label>
                        <input accept="image/*" type="file" name="avatar" id="id_avatar" style="display: none">
                        <span class="help-block"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button style="margin-left: 41%" type="button" class="btn btn-warning" id="reg-submit">注册</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script src="/static/js/jquery-3.3.1.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
<script>
    // 找到头像的input标签绑定change事件
    $("#id_avatar").change(function () {
        // 1. 创建一个读取文件的对象
        var fileReader = new FileReader();
        // 取到当前选中的头像文件
        // console.log(this.files[0]);
        // 读取你选中的那个文件
        fileReader.readAsDataURL(this.files[0]);  // 读取文件是需要时间的
        fileReader.onload = function () {
            // 2. 等上一步读完文件之后才 把图片加载到img标签中
            $("#avatar-img").attr("src", fileReader.result);
        };
    });
    // AJAX提交注册的数据
    $("#reg-submit").click(function () {
        // 取到用户填写的注册数据，向后端发送AJAX请求
        var formData = new FormData();
        formData.append("username", $("#id_username").val());
        formData.append("password", $("#id_password").val());
        formData.append("re_password", $("#id_re_password").val());
        formData.append("email", $("#id_email").val());
        formData.append("avatar", $("#id_avatar")[0].files[0]);
        formData.append("csrfmiddlewaretoken", $("[name='csrfmiddlewaretoken']").val());

        $.ajax({
            url: "/register/",
            type: "post",
            processData: false,
            contentType: false,
            data: formData,
            success: function (data) {
                if (data.status) {
                    // 有错误就展示错误
                    // console.log(data.msg);
                    // 将报错信息填写到页面上
                    $.each(data.msg, function (k, v) {
                        // console.log("id_"+k, v[0]);
                        // console.log($("#id_"+k));
                        $("#id_" + k).next("span").text(v[0]).parent().parent().addClass("has-error");
                    })

                } else {
                    // 没有错误就跳转到指定页面
                    location.href = data.msg;
                }
            }
        })
    });

    // 将所有的input框绑定获取焦点的事件，将所有的错误信息清空
    $("form input").focus(function () {
        $(this).next().text("").parent().parent().removeClass("has-error");
    });

    //当框内失去焦点后，ajax发送到后端数据库监测用户名是否存在
    $("#id_username").blur(function () {
        var username = $("#id_username").val();
        $.ajax({
            url: "/check_username_exist/",
            type: "get",
            data: {"username": username},
            success: function (data) {
                if (data.status) {
                    $("#id_username").next().text(data.msg).parent().parent().addClass("has-error");
                }
            }
        })
    })
</script>
</body>
</html>